### ISSUE TITLE
Cannot import 'get_data_window' from rasterio > 1.0a(x)

### ISSUE THREAD

**Issue by TaylorMutch** [consbio/clover#42]
Using `rasterio==1.0a5`,  the `get_data_window` method is no longer importable directly from `rasterio`. The equivalent function is now imported using the `windows` module, like the below (from [here](https://github.com/mapbox/rasterio/blob/19e1de74861e65ffc15489ea0c9e7d122a8e8fe9/tests/test_indexing.py#L85))
```
from rasterio import windows

def test_data_window_unmasked(data):
    window = windows.get_data_window(data)
    assert window == ((0, data.shape[0]), (0, data.shape[1]))
```
I'd have to dig into where that change was made, and it's not game-breaking right now, but it may be something to consider when using window operations.

**Comment by brendan-ward** [comment]
@TaylorMutch see `rasterio1.0` branch.

**Comment by TaylorMutch** [comment]
Thanks @brendan-ward!
