### ISSUE TITLE
Refactor rendering into dedicated library

### ISSUE THREAD

**Issue by brendan-ward** [consbio/clover#5]
I think the rendering stack should be moved into a separate dedicated library, and included as a dependency of clover.

**Comment by brendan-ward** [comment]
Possible name: [achiote](https://en.wikipedia.org/wiki/Bixa_orellana)

**Comment by nikmolnar** [comment]
What is the motivation for this? Is it so that the rendering could be used with other (non-NetCDF) data sources?

**Comment by brendan-ward** [comment]
Yes.  Already starting to shake out use cases related to rendering GeoTIFFs directly, but really it depends primarily on numpy, and is used by but does not depend on the NetCDF functionality in clover.

Doing this would allow me to build a plugin for rasterio's ```rio``` CLI - which is the current model for dynamically injecting non-core functionality.  [Example](https://github.com/mapbox/rio-mbtiles)

It also frees the rendering stack up to bring in Cython as needed, as well as other python color manipulation libs without adding these as direct requirements to clover.

**Comment by brendan-ward** [comment]
Was thinking ```yarr``` (yet another raster renderer)   had a nice ring to it, but it's overused on github.

Maybe ```npren``` (numpy renderer)?

**Comment by brendan-ward** [comment]
```numlimn```

**Comment by brendan-ward** [comment]
also investigate using ```pypng``` or ```purepng``` as a replacement for ```Pillow```, and adding pngquant with appropriate wrappers.

**Comment by brendan-ward** [comment]
For the moment, I've changed my mind.  Closing...
